name: Quarkus CI

on:
  push:
    branches-ignore:
      - 'dependabot/**'
    paths-ignore:
      - 'docs/src/main/asciidoc/**'
      - 'README.md'
      - 'CONTRIBUTING.md'
      - 'ADOPTERS.md'
      - 'LICENSE.txt'
      - 'dco.txt'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/autoissuelabeler.yml'
      - '.github/boring-cyborg.yml'
      - '.github/NativeBuildReport.kts'
      - '.dependabot/**'
  pull_request:
    types: [assigned, opened, synchronize, reopened, ready_for_review, edited]
    paths-ignore:
      - 'docs/src/main/asciidoc/**'
      - 'README.md'
      - 'CONTRIBUTING.md'
      - 'ADOPTERS.md'
      - 'LICENSE.txt'
      - 'dco.txt'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/autoissuelabeler.yml'
      - '.github/boring-cyborg.yml'
      - '.github/NativeBuildReport.kts'
      - '.dependabot/**'

env:
  # Workaround testsuite locale issue
  LANG: en_US.UTF-8
  NATIVE_TEST_MAVEN_OPTS: "-B --settings azure-mvn-settings.xml -Dquarkus.native.container-build=true -Dtest-postgresql -Dtest-elasticsearch -Dtest-keycloak -Dtest-dynamodb -Dtest-mysql -Dtest-mariadb -Dmariadb.url='jdbc:mariadb://localhost:3308/hibernate_orm_test'  -Dtest-mssql -Dtest-vault -Dtest-neo4j -Dnative-image.xmx=6g -Dnative -Dno-format install"
  JVM_TEST_MAVEN_OPTS: "-e -B --settings azure-mvn-settings.xml -Dtest-postgresql -Dtest-elasticsearch -Dtest-mysql -Dtest-mariadb -Dmariadb.url='jdbc:mariadb://localhost:3308/hibernate_orm_test'  -Dtest-mssql -Dtest-dynamodb -Dtest-vault -Dtest-neo4j -Dtest-keycloak -Dno-format"
  DB_USER: hibernate_orm_test
  DB_PASSWORD: hibernate_orm_test
  DB_NAME: hibernate_orm_test
jobs:
  build-jdk8:
    name: "JDK 8 Build"
    runs-on: ubuntu-latest
    # Skip draft PRs and those with WIP in the subject, rerun as soon as its removed
    if: "github.event_name != 'pull_request' || ( \
           github.event.pull_request.draft == false && \
           github.event.pull_request.state != 'closed' && \
           contains(github.event.pull_request.title, 'wip ') == false && \
           contains(github.event.pull_request.title, '[wip]') == false && \
           (
             github.event.action != 'edited' || \
             contains(github.event.changes.title.from, 'wip ') || \
             contains(github.event.changes.title.from, '[wip]') \
           ) \
         )"
    steps:
      - uses: actions/checkout@v2
      - uses: n1hility/cancel-previous-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up JDK 8
        # Uses sha for added security since tags can be updated
        uses: joschi/setup-jdk@7134ae95986e4e0a4f9f0b51345c93fcebfc4ea9
        with:
          java-version: openjdk8
      - name: Compute cache restore key
        # Always recompute on a push so that the maven repo doesnt grow indefinitely with old versions
        run: |
           if ${{ github.event_name == 'pull_request' }}; then echo "::set-env name=COMPUTED_RESTORE_KEY::q2maven-"; fi
      - name: Cache Maven Repository
        id: cache-maven
        uses: n1hility/cache@v2
        with:
          path: ~/.m2/repository
          # Improves the reusability of the cache to limit key changes
          key: q2maven-${{ hashFiles('bom/runtime/pom.xml') }}
          restore-keys: ${{ env.COMPUTED_RESTORE_KEY }}
          restore-only: ${{ github.event_name == 'pull_request' }}
      - name: Build
        run: |
          echo "@AGG disabled step: mvn -e -B  -DskipTests=true -Dno-format -DskipDocs clean install"
      - name: Invoke dependency checker
        shell: bash
        run: |
          echo "@AGG Inside of dependency checker task"
          echo "GITHUB_SHA=${GITHUB_SHA}"
          echo "GITHUB_REF=$GITHUB_REF"
          echo "GITHUB_HEAD_REF=$GITHUB_HEAD_REF"
          echo "GITHUB_BASE_REF=$GITHUB_BASE_REF"
          mvn -B -f independent-projects/utilities/dependency-checker/pom.xml package
          if ${{ github.event_name == 'pull_request' }}; then 
            echo "@AGG is a PR"
            DEP_CHECKER_BASE=$GITHUB_BASE_REF
            DEP_CHECKER_HEAD=$GITHUB_HEAD_REF
          else 
            echo "@AGG is a push"
            DEP_CHECKER_BASE="refs/heads/master"
            DEP_CHECKER_HEAD=$GITHUB_SHA
          fi
          echo "@AGG invoking tool with ${DEP_CHECKER_BASE} and ${DEP_CHECKER_HEAD}"
          java -jar independent-projects/utilities/dependency-checker/target/quarkus-utilities-dependency-checker-999-SNAPSHOT-jar-with-dependencies.jar ${DEP_CHECKER_BASE} ${DEP_CHECKER_HEAD}
          TOOL_OUTPUT=$(cat target/tests-to-run.txt)
          echo "@AGG tool output: $TESTS_TO_RUN"
       
  native-tests:
    name: Native Tests - ${{matrix.category}}
    needs: build-jdk8
    runs-on: ubuntu-latest
    # Ignore the following YAML Schema error 
    timeout-minutes: ${{matrix.timeout}}
    strategy:
      max-parallel: 8
      fail-fast: false
      matrix:
        category: [Main, Data1, Data2]
        include:
          - category: Main
            postgres: "true"
            timeout: 25
            test-modules: main
          - category: Data1
            mariadb: "true"
            mssql: "true"
            timeout: 50
            test-modules: >
              jpa-h2
              jpa-mariadb
              jpa-mssql
              jpa-derby
              jpa-without-entity
          - category: Data2
            mysql: "true"
            postgres: "true"
            timeout: 25
            test-modules: >
              jpa
              jpa-postgresql
              jpa-mysql
              reactive-mysql-client
    steps:
      - name: Print tests to run
        run: |
          echo "Inside native tests for ${{matrix.test-modules}}"
          TESTS_TO_RUN=$(cat target/tests-to-run.txt)
          echo "@AGG will run the tests: $TESTS_TO_RUN"
