name: "Quarkus Cron Native image"
on:
  schedule:
    - cron: '0 2 * * *'
  pull_request:
    branches:
      - master
  repository_dispatch:


jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        java: [ 11 ]
    name: build-and-testing
    steps:

      - name: Stop MySQL
        run: sudo systemctl stop mysql

      - name: Pull docker image
        run: docker pull quay.io/quarkus/ubi-quarkus-native-image:19.3.1-java${{ matrix.java }}

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Checkout Quarkus
        uses: actions/checkout@v2
        with:
          repository: aguibert/quarkus
          ref: smart-testing

      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run dependency checker
        run: |
          echo "@AGG Inside of dependency checker task"
          echo "GITHUB_SHA=${GITHUB_SHA}"
          echo "GITHUB_REF=$GITHUB_REF"
          echo "GITHUB_HEAD_REF=$GITHUB_HEAD_REF"
          echo "GITHUB_BASE_REF=$GITHUB_BASE_REF"
          mvn -B -f independent-projects/utilities/dependency-checker/pom.xml package
          java -jar independent-projects/utilities/dependency-checker/target/quarkus-utilities-dependency-checker-999-SNAPSHOT-jar-with-dependencies.jar ${GITHUB_BASE_REF} ${GITHUB_HEAD_REF}

      - name: Build Quarkus
        run: mvn -B install -DskipTests -DskipITs -Dno-format

      - name: Run integration tests in native
        run: |
          TESTS_TO_RUN=$(cat target/tests-to-run.txt)
          echo "@AGG will run the tests: $TESTS_TO_RUN"
          mvn -B --settings azure-mvn-settings.xml verify -f integration-tests/pom.xml $TESTS_TO_RUN -DskipTests  -Dno-format -Ddocker -Dnative -Dquarkus.native.container-build=true -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-native-image:19.3.1-java${{ matrix.java }} -Dtest-postgresql -Dtest-elasticsearch -Dtest-mysql -Dtest-dynamodb -Dtest-vault -Dtest-neo4j

